# Don't print a new line at the start of the prompt
add_newline = false
prompt_order=[
    "username",
    "hostname",
    "kubernetes",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "hg_branch",
    "package",
    "dotnet",
    "golang",
    "java",
    "nodejs",
    "php",
    "python",
    "ruby",
    "rust",
    "terraform",
    "nix_shell",
    "conda",
    "memory_usage",
    "aws",
    "env_var",
    "cmd_duration",
    "jobs",
    "time",
    "line_break",
    "battery",
    "character",
    ]

# Replace the "❯" symbol in the prompt with "➜"
# [character]      # The name of the module we are configuring is "character"
# symbol = "➜"     # The "symbol" segment is being set to "➜"

[line_break]
disabled = false

[kubernetes]
symbol = "⛵ stevedoreCtx:$(stevedore config show-context 2>&1 | rg kubernetesContext | awk '{ print $2 }') | ktx:"
style = "bold italic cyan"
disabled = false

[git_commit]
disabled = false

[git_state]
disabled = false 

[git_status]
disabled = false

[directory]
style = "bold green"

## Disabled 

[package]
disabled = true

[hg_branch]
disabled = true 

[dotnet]
disabled = true 

[golang]
disabled = true 

[java]
disabled = true 

[nodejs]
disabled = true 

[php]
disabled = true 

[python]
disabled = true 

[ruby]
disabled = true 

[rust]
disabled = true 

[terraform]
disabled = true 

[nix_shell]
disabled = true 

[conda]
disabled = true 
